export const personalInfo = {
  name: "Niaiko Rakotoarisoa",
  title: "Full Stack JavaScript Developer",
  tagline: "Building modern, scalable, and user-centric web applications",
  bio: "Passionate full-stack developer with 6+ years of experience crafting elegant solutions to complex problems. Specialized in Angular, React, NestJS, and modern web technologies. I love transforming ideas into reality through clean code and intuitive user experiences.",
  email: "niaikorakoto1001@gmail.com",
  phone: "+261 34 00 000 00",
  location: "Antananarivo, Madagascar",
  availability: "Available for freelance projects",
  cv: "/cv.pdf",
  social: {
    github: "https://github.com/niaiko-rakoto",
    linkedin: "https://linkedin.com/in/niaiko-rakoto",
    twitter: "https://twitter.com/niaiko-rakoto",
    instagram: "https://instagram.com/niaiko-rakoto",
  },
};

export const skills = {
  languages: [
    { name: "JavaScript", level: 95, icon: "SiJavascript" },
    { name: "TypeScript", level: 95, icon: "SiTypescript" },
    { name: "HTML5", level: 95, icon: "SiHtml5" },
    { name: "CSS3", level: 90, icon: "SiCss3" },
    { name: "Python", level: 70, icon: "SiPython" },
  ],
  frontend: [
    { name: "Angular", level: 95, icon: "SiAngular" },
    { name: "React", level: 95, icon: "SiReact" },
    { name: "Next.js", level: 90, icon: "SiNextdotjs" },
    { name: "Tailwind CSS", level: 90, icon: "SiTailwindcss" },
    { name: "Redux", level: 90, icon: "SiRedux" },
  ],
  backend: [
    { name: "NestJS", level: 95, icon: "SiNestjs" },
    { name: "Node.js", level: 95, icon: "SiNodedotjs" },
    { name: "Strapi", level: 85, icon: "SiStrapi" },
    { name: "GraphQL", level: 90, icon: "SiGraphql" },
    { name: "REST API", level: 95, icon: "SiOpenapi" },
    { name: "Microservices", level: 85, icon: "SiMicroservices" },
    { name: "PostgreSQL", level: 90, icon: "SiPostgresql" },
    { name: "MongoDB", level: 90, icon: "SiMongodb" },
  ],
  tools: [
    { name: "Git", level: 95, icon: "SiGit" },
    { name: "Docker", level: 85, icon: "SiDocker" },
    { name: "AWS", level: 80, icon: "SiAmazonaws" },
    { name: "Figma", level: 80, icon: "SiFigma" },
  ],
};

export const stats = [
  { label: "Total Projects", value: "50+", icon: "FaCode" },
  { label: "Happy Clients", value: "30+", icon: "FaSmile" },
  { label: "Years Experience", value: "6+", icon: "FaBriefcase" },
  { label: "Technologies", value: "25+", icon: "FaTools" },
];

export const projects = [
  {
    id: 1,
    title: "E-Commerce Platform",
    description: "A full-featured e-commerce platform with payment integration, inventory management, and admin dashboard. Built with modern technologies for optimal performance.",
    image: "https://images.unsplash.com/photo-1557821552-17105176677c?w=800&q=80",
    tech: ["Next.js", "TypeScript", "Stripe", "PostgreSQL", "Tailwind CSS"],
    category: "Web App",
    github: "https://github.com/alexandredupont/ecommerce",
    live: "https://ecommerce-demo.vercel.app",
    featured: true,
  },
  {
    id: 2,
    title: "Task Management System",
    description: "Real-time collaborative task management tool with drag-and-drop interface, team collaboration features, and advanced analytics.",
    image: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=800&q=80",
    tech: ["React", "Node.js", "Socket.io", "MongoDB", "Material-UI"],
    category: "Web App",
    github: "https://github.com/alexandredupont/taskmanager",
    live: "https://taskmanager-demo.vercel.app",
    featured: true,
  },
  {
    id: 3,
    title: "Social Media Dashboard",
    description: "Analytics dashboard for social media management with real-time data visualization, post scheduling, and engagement metrics.",
    image: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&q=80",
    tech: ["Vue.js", "Express", "Chart.js", "Redis", "Vuetify"],
    category: "Dashboard",
    github: "https://github.com/alexandredupont/social-dashboard",
    live: "https://social-dashboard-demo.vercel.app",
    featured: true,
  },
  {
    id: 4,
    title: "Weather Forecast App",
    description: "Beautiful weather application with 7-day forecast, location-based weather, and interactive maps.",
    image: "https://images.unsplash.com/photo-1561484930-998b6a7b22e8?w=800&q=80",
    tech: ["React", "OpenWeather API", "Mapbox", "Styled Components"],
    category: "Mobile App",
    github: "https://github.com/alexandredupont/weather-app",
    live: "https://weather-app-demo.vercel.app",
    featured: false,
  },
  {
    id: 5,
    title: "Blog Platform",
    description: "Modern blogging platform with markdown support, comments system, and SEO optimization.",
    image: "https://images.unsplash.com/photo-1499750310107-5fef28a66643?w=800&q=80",
    tech: ["Next.js", "MDX", "PostgreSQL", "Prisma", "Tailwind CSS"],
    category: "Web App",
    github: "https://github.com/alexandredupont/blog-platform",
    live: "https://blog-platform-demo.vercel.app",
    featured: false,
  },
  {
    id: 6,
    title: "Fitness Tracker",
    description: "Personal fitness tracking application with workout plans, progress tracking, and nutrition logging.",
    image: "https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=800&q=80",
    tech: ["React Native", "Firebase", "Redux", "Expo"],
    category: "Mobile App",
    github: "https://github.com/alexandredupont/fitness-tracker",
    live: "https://fitness-tracker-demo.vercel.app",
    featured: false,
  },
];

export const experience = [
  {
    id: 1,
    role: "Senior Full Stack Developer",
    company: "Tech Innovation Labs",
    location: "Paris, France",
    period: "2022 - Present",
    description: "Leading development of enterprise web applications using React, Node.js, and cloud technologies. Mentoring junior developers and implementing best practices.",
    achievements: [
      "Architected and deployed 5+ major projects serving 100k+ users",
      "Reduced application load time by 60% through optimization",
      "Implemented CI/CD pipeline improving deployment efficiency by 80%",
    ],
    type: "work",
  },
  {
    id: 2,
    role: "Full Stack Developer",
    company: "Digital Solutions Inc.",
    location: "Lyon, France",
    period: "2021 - 2022",
    description: "Developed and maintained multiple client projects, focusing on React frontend and Node.js backend development.",
    achievements: [
      "Built 10+ responsive web applications from scratch",
      "Improved code quality through implementing automated testing",
      "Collaborated with cross-functional teams in Agile environment",
    ],
    type: "work",
  },
  {
    id: 3,
    role: "Junior Web Developer",
    company: "StartUp Studio",
    location: "Remote",
    period: "2020 - 2021",
    description: "Started career developing websites and web applications for small businesses and startups.",
    achievements: [
      "Developed 15+ websites using modern web technologies",
      "Learned and applied best practices in web development",
      "Gained experience in client communication and project management",
    ],
    type: "work",
  },
  {
    id: 4,
    role: "Full Stack Development Bootcamp",
    company: "Le Wagon Paris",
    location: "Paris, France",
    period: "2020",
    description: "Intensive 9-week coding bootcamp learning full-stack web development.",
    achievements: [
      "Mastered Ruby on Rails, JavaScript, HTML/CSS",
      "Built 3 full-stack web applications",
      "Graduated top 10% of cohort",
    ],
    type: "education",
  },
];

export const certificates = [
  {
    id: 1,
    name: "Advanced React & Redux",
    issuer: "Udemy - Maximilian Schwarzmüller",
    date: "2023",
    credential: "UC-REACT-2023-001",
  },
  {
    id: 2,
    name: "Node.js - The Complete Guide",
    issuer: "Udemy - Andrew Mead",
    date: "2023",
    credential: "UC-NODEJS-2023-002",
  },
  {
    id: 3,
    name: "NestJS: The Complete Developer's Guide",
    issuer: "Udemy - Stephen Grider",
    date: "2023",
    credential: "UC-NESTJS-2023-003",
  },
  {
    id: 4,
    name: "AWS Certified Developer - Associate",
    issuer: "Amazon Web Services",
    date: "2024",
    credential: "AWS-DEV-2024-004",
  },
  {
    id: 5,
    name: "Docker & Kubernetes: The Complete Guide",
    issuer: "Udemy - Stephen Grider",
    date: "2023",
    credential: "UC-DOCKER-2023-005",
  },
  {
    id: 6,
    name: "TypeScript: The Complete Developer's Guide",
    issuer: "Udemy - Stephen Grider",
    date: "2022",
    credential: "UC-TS-2022-006",
  },
];
