export const personalInfo = {
  name: "Niaiko Rakotoarisoa",
  title: "Full Stack JavaScript Developer",
  tagline: "Building modern, scalable, and user-centric web applications",
  bio: "Passionate full-stack developer with 6+ years of experience crafting elegant solutions to complex problems. Specialized in Angular, React, NestJS, and modern web technologies. I love transforming ideas into reality through clean code and intuitive user experiences.",
  email: "niaikorakoto1001@gmail.com",
  phone: "+261 34 00 000 00",
  location: "Antananarivo, Madagascar",
  availability: "Available for freelance projects",
  cv: "/cv.pdf",
  social: {
    github: "https://github.com/niaiko-rakoto",
    linkedin: "https://linkedin.com/in/niaiko-rakoto",
    twitter: "https://twitter.com/niaiko-rakoto",
    instagram: "https://instagram.com/niaiko-rakoto",
  },
};

export const skills = {
  languages: [
    { name: "JavaScript", level: 95, icon: "SiJavascript" },
    { name: "TypeScript", level: 95, icon: "SiTypescript" },
    { name: "HTML5", level: 95, icon: "SiHtml5" },
    { name: "CSS3", level: 90, icon: "SiCss3" },
    { name: "Python", level: 70, icon: "SiPython" },
  ],
  frontend: [
    { name: "Angular", level: 95, icon: "SiAngular" },
    { name: "React", level: 95, icon: "SiReact" },
    { name: "Next.js", level: 90, icon: "SiNextdotjs" },
    { name: "Tailwind CSS", level: 90, icon: "SiTailwindcss" },
    { name: "Redux", level: 90, icon: "SiRedux" },
  ],
  backend: [
    { name: "NestJS", level: 95, icon: "SiNestjs" },
    { name: "Node.js", level: 95, icon: "SiNodedotjs" },
    { name: "Strapi", level: 85, icon: "SiStrapi" },
    { name: "GraphQL", level: 90, icon: "SiGraphql" },
    { name: "REST API", level: 95, icon: "SiOpenapi" },
    { name: "Microservices", level: 85, icon: "SiMicroservices" },
    { name: "PostgreSQL", level: 90, icon: "SiPostgresql" },
    { name: "MongoDB", level: 90, icon: "SiMongodb" },
  ],
  tools: [
    { name: "Git", level: 95, icon: "SiGit" },
    { name: "Docker", level: 85, icon: "SiDocker" },
    { name: "AWS", level: 80, icon: "SiAmazonaws" },
    { name: "Figma", level: 80, icon: "SiFigma" },
  ],
};

export const stats = [
  { label: "Total Projects", value: "50+", icon: "FaCode" },
  { label: "Happy Clients", value: "30+", icon: "FaSmile" },
  { label: "Years Experience", value: "6+", icon: "FaBriefcase" },
  { label: "Technologies", value: "25+", icon: "FaTools" },
];

export const projects = [
  {
    id: 1,
    title: "E-Commerce Platform",
    description: "A full-featured e-commerce platform with payment integration, inventory management, and admin dashboard. Built with modern technologies for optimal performance.",
    image: "https://images.unsplash.com/photo-1557821552-17105176677c?w=800&q=80",
    tech: ["Next.js", "TypeScript", "Stripe", "PostgreSQL", "Tailwind CSS"],
    category: "Web App",
    github: "https://github.com/alexandredupont/ecommerce",
    live: "https://ecommerce-demo.vercel.app",
    featured: true,
  },
  {
    id: 2,
    title: "Task Management System",
    description: "Real-time collaborative task management tool with drag-and-drop interface, team collaboration features, and advanced analytics.",
    image: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=800&q=80",
    tech: ["React", "Node.js", "Socket.io", "MongoDB", "Material-UI"],
    category: "Web App",
    github: "https://github.com/alexandredupont/taskmanager",
    live: "https://taskmanager-demo.vercel.app",
    featured: true,
  },
  {
    id: 3,
    title: "Social Media Dashboard",
    description: "Analytics dashboard for social media management with real-time data visualization, post scheduling, and engagement metrics.",
    image: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&q=80",
    tech: ["Vue.js", "Express", "Chart.js", "Redis", "Vuetify"],
    category: "Dashboard",
    github: "https://github.com/alexandredupont/social-dashboard",
    live: "https://social-dashboard-demo.vercel.app",
    featured: true,
  },
  {
    id: 4,
    title: "Weather Forecast App",
    description: "Beautiful weather application with 7-day forecast, location-based weather, and interactive maps.",
    image: "https://images.unsplash.com/photo-1561484930-998b6a7b22e8?w=800&q=80",
    tech: ["React", "OpenWeather API", "Mapbox", "Styled Components"],
    category: "Mobile App",
    github: "https://github.com/alexandredupont/weather-app",
    live: "https://weather-app-demo.vercel.app",
    featured: false,
  },
  {
    id: 5,
    title: "Blog Platform",
    description: "Modern blogging platform with markdown support, comments system, and SEO optimization.",
    image: "https://images.unsplash.com/photo-1499750310107-5fef28a66643?w=800&q=80",
    tech: ["Next.js", "MDX", "PostgreSQL", "Prisma", "Tailwind CSS"],
    category: "Web App",
    github: "https://github.com/alexandredupont/blog-platform",
    live: "https://blog-platform-demo.vercel.app",
    featured: false,
  },
  {
    id: 6,
    title: "Fitness Tracker",
    description: "Personal fitness tracking application with workout plans, progress tracking, and nutrition logging.",
    image: "https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=800&q=80",
    tech: ["React Native", "Firebase", "Redux", "Expo"],
    category: "Mobile App",
    github: "https://github.com/alexandredupont/fitness-tracker",
    live: "https://fitness-tracker-demo.vercel.app",
    featured: false,
  },
];

export const experience = [
  {
    id: 1,
    role: "Senior Full Stack Developer",
    company: "Keobiz Madagascar",
    location: "Antananarivo, Madagascar",
    period: "May 2025 - Present",
    description: "Développement et maintenance d'une application web d'entreprise complète pour la gestion d'affaires avec Angular et Node.js/Express. Intégration avec Salesforce et systèmes de paiement.",
    achievements: [
      "Architecture modulaire Angular avec signals réactifs, réduisant les erreurs de 70%",
      "Résolution de problèmes critiques pour 10 000+ utilisateurs actifs",
      "Optimisation des filtres et composants, améliorant la vitesse de 50%",
      "Mise en place de pipelines CI/CD pour déploiements plus rapides",
      "Intégration d'APIs full-stack pour la gestion des rôles et exports"
    ],
    technologies: "Angular, TypeScript, Node.js, Express, RxJS, Angular Material, PostgreSQL, Docker, Git",
    type: "work",
  },
  {
    id: 2,
    role: "Full Stack Developer",
    company: "eTech consulting",
    location: "Antananarivo, Madagascar",
    period: "Mars 2022 - Mai 2025",
    description: "Développement et maintenance de plusieurs projets clients, focalisé sur le développement frontend React et backend Node.js.",
    achievements: [
      "Construction de 10+ applications web responsives de zéro",
      "Application mobile avec React Native pour des ventes et locations immobilières",
      "Amélioration de la qualité du code grâce à l'implémentation de tests automatisés",
      "Collaboration avec des équipes interfonctionnelles dans un environnement Agile",
    ],
    technologies: "React, Node.js, NestJS, Strapi, Express, TypeScript, React Native, GraphQL, REST API, Microservices, PostgreSQL, Docker, Git",
    type: "work",
  },
  {
    id: 3,
    role: "Full Stack Developer",
    company: "Onirique Factory LTD",
    location: "Antananarivo, Madagascar",
    period: "Mai 2021 - Mars 2022",
    description: "Conception et optimisation d'applications web modernes, en collaboration avec des équipes pluridisciplinaires pour des solutions robustes.",
    achievements: [
      "Développement d'APIs REST et GraphQL sécurisées avec Node.js et NestJS.",
      "Amélioration des performances backend via optimisation des requêtes SQL et gestion des index.",
      "Création d'interfaces réactives et ergonomiques avec Angular.",
    ],
    technologies: "Angular, Node.js, NestJS, Vendure, Express, TypeScript, GraphQL, REST API, MySQL, Docker, Git",
    type: "work",
  },
  {
    id: 4,
    role: "Frontend Developer",
    company: "HR IT Consulting",
    location: "Antananarivo, Madagascar",
    period: "Juillet 2019 - Mai 2021",
    description: "Contribution au développement d'interfaces utilisateur pour applications web, en collaboration avec des développeurs expérimentés pour des conceptions réactives et une meilleure expérience utilisateur.",
    achievements: [
      "Intégration d'APIs REST et WebSockets pour des applications interactives en temps réel.",
      "Amélioration de l'accessibilité et respect des bonnes pratiques UX/UI.",
      "Création d'interfaces réactives et ergonomiques avec Angular.",
    ],
    technologies: "Angular, HTML, CSS, JavaScript, TypeScript, Angular Material, RxJS, Angular Animations, Angular Testing, Angular Performance Optimization, Angular Security, Angular Best Practices",
    type: "work",
  },
];

export const certificates = [
  {
    id: 1,
    name: "Data Privacy Fundamentals",
    issuer: "Fireside Analytics Inc.",
    date: "2025",
    credential: "DS0301EN",
    pdfUrl: "/certificate/Data Privacy Fundamentals DS0301EN, provided by Fireside Analytics Inc.pdf",
    verifyUrl: "https://courses.cognitiveclass.ai/certificates/ef64e32ad2764dde911848c8b024f7b0",
  },
  {
    id: 2,
    name: "Docker Essentials - A Developer Introduction",
    issuer: "IBM",
    date: "2023",
    credential: "CO0101EN",
    pdfUrl: "/certificate/Docker Essentials- A Developer Introduction - CO0101EN, provided by IBM.pdf",
    verifyUrl: "https://courses.cognitiveclass.ai/certificates/88338a6e9731448198398045f8ba0e35",
  },
  {
    id: 3,
    name: "NoSQL and DBaaS 101",
    issuer: "IBM",
    date: "2023",
    credential: "DB0151EN",
    pdfUrl: "/certificate/NoSQL and DBaaS 101 DB0151EN, provided by IBM.pdf",
    verifyUrl: "https://courses.cognitiveclass.ai/certificates/5cfed504cc9f42738ac0833709b068ea",
  },
  {
    id: 4,
    name: "English for Science, Technology, Engineering, and Mathematics (STEM)",
    issuer: "MOOC Platform",
    date: "2024",
    credential: "STEM-ENG-2022",
    pdfUrl: "/certificate/STEM MOOC.pdf",
    verifyUrl: "https://badges.parchment.com/public/assertions/cOQd3haKQnKtqoLmS0uoeg?identity__email=niaikorakoto1001%40gmail.com",
  },
];
